# Generated by Django 3.1.5 on 2021-01-12 14:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('slug', models.SlugField(editable=False)),
                ('about', models.CharField(help_text='maximum 255 characters', max_length=255)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(help_text="Don't include country code", max_length=10)),
                ('friends', models.ManyToManyField(blank=True, null=True, to='facebook.Person')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
