# Generated by Django 3.1.5 on 2021-01-12 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20210113_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='viewed',
            new_name='seen',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groups',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups'),
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
