# Generated by Django 3.1.5 on 2021-01-12 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20210113_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
